In [ ]:
numpy 提供了一种数组类型

In [2]:
import numpy as np

In [2]:
np.__version__

'2.0.0'

In [3]:
[1,3.12,'hello']

[1, 3.12, 'hello']

In [4]:
# numpy的数组
array = np.array([1,3.14,'hello'])

In [5]:
array

array(['1', '3.14', 'hello'], dtype='<U32')

In [8]:
names = ["wood","Iing","jaca"]
array1= np.array(names)
array1

array(['wood', 'Iing', 'jaca'], dtype='<U4')

In [10]:
age = [14, 12, 18]
array3 = np.array(age,dtype=np.float32)
array3

array([14., 12., 18.], dtype=float32)

In [11]:
money = [[1,2,4],[3,4,5]]
np.array(money)

array([[1, 2, 4],
       [3, 4, 5]])

In [ ]:
shape = (m,n)  m行n列 二位数组
shape = (m)   m个元素的一维数组  [1,2,4]
shape = (m,)   m个元素的一维数组
shape = (m,1)   m行1列   二维数组 [[2],[1],[4]]
shape = (1,m)    1行m列   二维数组 [[1,2,4]]

In [13]:
# 构造一个4行3列的二维数组
np.ones(shape=(4,3),dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [14]:
# 构造一个长度为3的一维数组
np.ones(shape=(3))

array([1., 1., 1.])

In [15]:
# 构造一个5行1列的二维数组
np.ones(shape=(5,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [16]:
# 构造一个1行3列的二维数组
np.ones(shape=(1,3))

array([[1., 1., 1.]])

In [17]:
np.zeros(shape=(5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.zeros(shape=(2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [19]:
np.full(shape=(2,3), fill_value=6)

array([[6, 6, 6],
       [6, 6, 6]])

In [21]:
# 单位矩阵 l2正则项
# 生成一个3阶单位矩阵
np.eye(N=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(N=5,M=4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [23]:
np.eye(N=5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.eye(N=5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [28]:
# 等差数列
np.linspace(0,10,10,endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
np.arange(0,10,step=1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# size同shape，生成随机整数
np.random.randint(1,100,size=(4,5))

array([[66, 78, 15, 57, 46],
       [ 3, 51, 15,  4, 26],
       [28, 22, 61, 70, 37],
       [76, 92, 48, 72, 14]], dtype=int32)

In [34]:
# 标准正态分布
np.random.randn(3,5)

array([[ 1.21548495,  0.82999209,  0.62859649,  0.64341827,  0.54208123],
       [-0.48525792, -0.00931409,  0.8257309 ,  2.34860312,  1.54544885],
       [-1.78255514,  0.51687376, -0.02964029,  0.73664506,  0.59319884]])

In [44]:
np.random.normal(loc=170, scale=5,size=(4,5))

array([[160.90537794, 164.63841953, 175.58138074, 175.00618989,
        171.53732721],
       [172.51444015, 167.38767012, 164.00067046, 168.77310834,
        160.34910833],
       [165.85844408, 168.09937988, 178.51833123, 171.33520561,
        169.42249786],
       [166.98475347, 165.97322908, 171.34579832, 167.86405456,
        170.22692359]])

In [47]:
# 生成随机小数
np.random.random(size=(10,10))

array([[0.94055076, 0.2244139 , 0.83537637, 0.87965797, 0.01906465,
        0.56501846, 0.9300403 , 0.44500774, 0.66870411, 0.0855525 ],
       [0.51153582, 0.16142746, 0.31090487, 0.28328756, 0.37805676,
        0.44212073, 0.62163804, 0.33052196, 0.7457206 , 0.65093497],
       [0.41768896, 0.42246464, 0.49682919, 0.27177274, 0.61830563,
        0.68794529, 0.08081365, 0.76588184, 0.28406509, 0.66987898],
       [0.44019251, 0.27313663, 0.72499328, 0.0714184 , 0.71732039,
        0.12638258, 0.71988738, 0.94522191, 0.40090839, 0.1185589 ],
       [0.90875195, 0.5136661 , 0.70872056, 0.55241892, 0.68095575,
        0.34693305, 0.27035222, 0.69879674, 0.61238843, 0.33340525],
       [0.20180006, 0.18448093, 0.62741932, 0.98933253, 0.59649044,
        0.42580249, 0.01231721, 0.30626657, 0.35071998, 0.45875318],
       [0.92260336, 0.69724559, 0.13930562, 0.65616861, 0.20186399,
        0.53429352, 0.51683709, 0.72562664, 0.43366104, 0.1133584 ],
       [0.30794267, 0.59818214, 0.6633765

In [3]:
# 生成一组随机索引，很好用
np.random.permutation(10)

array([3, 4, 1, 7, 5, 2, 9, 0, 8, 6], dtype=int32)

In [4]:
arr = np.random.randint(0,100,size=(4,5,3))

In [5]:
arr.ndim

3

In [6]:
arr.size

60

In [7]:
arr.shape

(4, 5, 3)

In [11]:
# 获取数组元素类型
arr.dtype

dtype('int32')

In [10]:
# 获取数组类型
type(arr)

numpy.ndarray

In [21]:
data = [[1,2,3,6,1],[1,2,3,4,5]]

In [17]:
data[0][2]

3

In [18]:
arr1 = np.array([1,3,5,6,7])

In [19]:
arr1[3]

np.int64(6)

In [22]:
arr2 = np.array(data)

In [26]:
# 列表的访问方式
arr2[0][0]

np.int64(1)

In [29]:
# numpy特有的
# arr[m,n...] 描述对应维度的索引值
arr2[0,0]

np.int64(1)

In [28]:
arr2[1,3]

np.int64(4)

In [30]:
# 高级用法
arr1

array([1, 3, 5, 6, 7])

In [35]:
# 使用列表作为索引访问
arr1[[0,1,2,0,1,2]]

array([1, 3, 5, 1, 3, 5])

In [38]:
# 使用BOOL列表作为索引访问 True对应的值会被返回
bool_list = [True, False, True, False,True]
arr1[bool_list]

array([1, 5, 7])

In [40]:
# eg.获取数组当中大于5的数
arr1[arr1>5]

array([6, 7])

In [44]:
arr3 = np.random.randint(0,10,size=(5,4,3))
arr3

array([[[9, 1, 1],
        [5, 7, 4],
        [9, 5, 4],
        [3, 1, 0]],

       [[5, 0, 0],
        [5, 7, 9],
        [2, 2, 5],
        [7, 4, 3]],

       [[0, 9, 8],
        [8, 7, 8],
        [9, 7, 3],
        [0, 5, 6]],

       [[9, 1, 6],
        [4, 3, 9],
        [6, 6, 4],
        [2, 1, 7]],

       [[1, 4, 7],
        [7, 4, 9],
        [4, 7, 5],
        [9, 0, 4]]], dtype=int32)

In [45]:
arr3[2,0]

array([0, 9, 8], dtype=int32)

In [46]:
arr3[0,1,2]

np.int32(4)

In [47]:
arr3[4]

array([[1, 4, 7],
       [7, 4, 9],
       [4, 7, 5],
       [9, 0, 4]], dtype=int32)

In [48]:
# 赋值和访问没有区别，都可以使用

In [51]:
# 所有的切片方式都是开区（左闭右开）
arr1[0:3]

array([1, 3, 5])

In [52]:
arr2

array([[1, 2, 3, 6, 1],
       [1, 2, 3, 4, 5]])

In [54]:
arr2 = np.random.randint(0,100,size=(5,6))
arr2

array([[15, 61,  2, 67, 57, 24],
       [68, 26,  1, 22, 31, 12],
       [40, 92, 96, 25, 14, 30],
       [87, 24, 79, 36, 26, 37],
       [21, 60, 48, 81, 71, 45]], dtype=int32)

In [56]:
# 行切片
arr2[0:2]

array([[15, 61,  2, 67, 57, 24],
       [68, 26,  1, 22, 31, 12]], dtype=int32)

In [57]:
# 列切片 不论多少维，每一个维度的切片范围都是用:表示，逗号分割。最后一个维度可以省略
arr2[:,0:2]

array([[15, 61],
       [68, 26],
       [40, 92],
       [87, 24],
       [21, 60]], dtype=int32)

In [58]:
arr3

array([[[9, 1, 1],
        [5, 7, 4],
        [9, 5, 4],
        [3, 1, 0]],

       [[5, 0, 0],
        [5, 7, 9],
        [2, 2, 5],
        [7, 4, 3]],

       [[0, 9, 8],
        [8, 7, 8],
        [9, 7, 3],
        [0, 5, 6]],

       [[9, 1, 6],
        [4, 3, 9],
        [6, 6, 4],
        [2, 1, 7]],

       [[1, 4, 7],
        [7, 4, 9],
        [4, 7, 5],
        [9, 0, 4]]], dtype=int32)

In [59]:
arr3[0:2]

array([[[9, 1, 1],
        [5, 7, 4],
        [9, 5, 4],
        [3, 1, 0]],

       [[5, 0, 0],
        [5, 7, 9],
        [2, 2, 5],
        [7, 4, 3]]], dtype=int32)

In [60]:
# 切割每个二位数组的前两列
arr3[:,:,0:2]

array([[[9, 1],
        [5, 7],
        [9, 5],
        [3, 1]],

       [[5, 0],
        [5, 7],
        [2, 2],
        [7, 4]],

       [[0, 9],
        [8, 7],
        [9, 7],
        [0, 5]],

       [[9, 1],
        [4, 3],
        [6, 6],
        [2, 1]],

       [[1, 4],
        [7, 4],
        [4, 7],
        [9, 0]]], dtype=int32)

In [61]:
# 切割每一个二位数组的前两行
arr3[:,0:2]

array([[[9, 1, 1],
        [5, 7, 4]],

       [[5, 0, 0],
        [5, 7, 9]],

       [[0, 9, 8],
        [8, 7, 8]],

       [[9, 1, 6],
        [4, 3, 9]],

       [[1, 4, 7],
        [7, 4, 9]]], dtype=int32)

In [62]:
arr3

array([[[9, 1, 1],
        [5, 7, 4],
        [9, 5, 4],
        [3, 1, 0]],

       [[5, 0, 0],
        [5, 7, 9],
        [2, 2, 5],
        [7, 4, 3]],

       [[0, 9, 8],
        [8, 7, 8],
        [9, 7, 3],
        [0, 5, 6]],

       [[9, 1, 6],
        [4, 3, 9],
        [6, 6, 4],
        [2, 1, 7]],

       [[1, 4, 7],
        [7, 4, 9],
        [4, 7, 5],
        [9, 0, 4]]], dtype=int32)

In [63]:
arr3[1:3,0]

array([[5, 0, 0],
       [0, 9, 8]], dtype=int32)

In [64]:
arr1

array([1, 3, 5, 6, 7])

In [65]:
arr1[::-1]

array([7, 6, 5, 3, 1])

In [68]:
arr2

array([[15, 61,  2, 67, 57, 24],
       [68, 26,  1, 22, 31, 12],
       [40, 92, 96, 25, 14, 30],
       [87, 24, 79, 36, 26, 37],
       [21, 60, 48, 81, 71, 45]], dtype=int32)

In [69]:
arr2[::-1]

array([[21, 60, 48, 81, 71, 45],
       [87, 24, 79, 36, 26, 37],
       [40, 92, 96, 25, 14, 30],
       [68, 26,  1, 22, 31, 12],
       [15, 61,  2, 67, 57, 24]], dtype=int32)

In [70]:
arr2[:,::-1]

array([[24, 57, 67,  2, 61, 15],
       [12, 31, 22,  1, 26, 68],
       [30, 14, 25, 96, 92, 40],
       [37, 26, 36, 79, 24, 87],
       [45, 71, 81, 48, 60, 21]], dtype=int32)

In [72]:
arr  = np.random.randint(0,10,size=(20))
arr

array([6, 0, 2, 2, 5, 1, 3, 7, 7, 6, 0, 2, 5, 1, 5, 3, 7, 2, 5, 6],
      dtype=int32)

In [75]:
arr.reshape((4,5))

array([[6, 0, 2, 2, 5],
       [1, 3, 7, 7, 6],
       [0, 2, 5, 1, 5],
       [3, 7, 2, 5, 6]], dtype=int32)

In [77]:
arr1= np.random.randint(0,10,size=(3,3))
arr2 = np.random.randint(10,20,size=(3,3))
display(arr1,arr2)

array([[5, 3, 7],
       [3, 0, 8],
       [5, 7, 4]], dtype=int32)

array([[17, 19, 19],
       [18, 19, 17],
       [12, 10, 15]], dtype=int32)

In [79]:
# 使用axis控制连接方向，axis指的是链接的维度
# axis 注意轴 非常常见
np.concatenate((arr1,arr2),axis=1)

array([[ 5,  3,  7, 17, 19, 19],
       [ 3,  0,  8, 18, 19, 17],
       [ 5,  7,  4, 12, 10, 15]], dtype=int32)

In [80]:
np.hstack((arr1,arr2))

array([[ 5,  3,  7, 17, 19, 19],
       [ 3,  0,  8, 18, 19, 17],
       [ 5,  7,  4, 12, 10, 15]], dtype=int32)

In [82]:
np.vstack((arr1,arr2))

array([[ 5,  3,  7],
       [ 3,  0,  8],
       [ 5,  7,  4],
       [17, 19, 19],
       [18, 19, 17],
       [12, 10, 15]], dtype=int32)

In [ ]:
【注意】：级联的时候
            如果是横向级联，参与级联的数组的行数要一致
            纵向级联，参与级联数组的列数要一致
            如果是高维数组的级联，级联的维度数据个数要一致

In [83]:
arr

array([6, 0, 2, 2, 5, 1, 3, 7, 7, 6, 0, 2, 5, 1, 5, 3, 7, 2, 5, 6],
      dtype=int32)

In [85]:
arr = np.random.randint(0,100,size=(6,6))
arr

array([[71, 86, 73, 89, 77, 93],
       [22, 64, 36, 73, 21, 28],
       [13, 10, 23, 75, 52, 66],
       [78, 65, 37, 63, 83, 29],
       [29, 18, 74, 24, 72, 58],
       [45, 44, 32, 36, 46, 33]], dtype=int32)

In [86]:
# 直接指定切分的份数
p1,p2 = np.split(arr, indices_or_sections=2)
display(p1,p2)

array([[71, 86, 73, 89, 77, 93],
       [22, 64, 36, 73, 21, 28],
       [13, 10, 23, 75, 52, 66]], dtype=int32)

array([[78, 65, 37, 63, 83, 29],
       [29, 18, 74, 24, 72, 58],
       [45, 44, 32, 36, 46, 33]], dtype=int32)

In [87]:
# 使用axis控制切分方向
p1,p2 = np.split(arr, indices_or_sections=2,axis=1)
display(p1,p2)

array([[71, 86, 73],
       [22, 64, 36],
       [13, 10, 23],
       [78, 65, 37],
       [29, 18, 74],
       [45, 44, 32]], dtype=int32)

array([[89, 77, 93],
       [73, 21, 28],
       [75, 52, 66],
       [63, 83, 29],
       [24, 72, 58],
       [36, 46, 33]], dtype=int32)

In [89]:
p1,p2,p3= np.split(arr, indices_or_sections=3,axis=1)
display(p1,p2,p3)

array([[71, 86],
       [22, 64],
       [13, 10],
       [78, 65],
       [29, 18],
       [45, 44]], dtype=int32)

array([[73, 89],
       [36, 73],
       [23, 75],
       [37, 63],
       [74, 24],
       [32, 36]], dtype=int32)

array([[77, 93],
       [21, 28],
       [52, 66],
       [83, 29],
       [72, 58],
       [46, 33]], dtype=int32)

In [90]:
arr2 = np.random.randint(0,100,size=(3,7))
arr2

array([[77, 99,  1,  9, 14,  2, 91],
       [67, 69, 81, 53, 12, 56, 81],
       [42, 40, 27, 18, 81, 81, 16]], dtype=int32)

In [91]:
p1,p2,p3= np.split(arr2, indices_or_sections=[2,5],axis=1)
display(p1,p2,p3)

array([[77, 99],
       [67, 69],
       [42, 40]], dtype=int32)

array([[ 1,  9, 14],
       [81, 53, 12],
       [27, 18, 81]], dtype=int32)

array([[ 2, 91],
       [56, 81],
       [81, 16]], dtype=int32)

In [92]:
arr2

array([[77, 99,  1,  9, 14,  2, 91],
       [67, 69, 81, 53, 12, 56, 81],
       [42, 40, 27, 18, 81, 81, 16]], dtype=int32)

In [93]:
np.hsplit(arr2,indices_or_sections=[2,5])

[array([[77, 99],
        [67, 69],
        [42, 40]], dtype=int32),
 array([[ 1,  9, 14],
        [81, 53, 12],
        [27, 18, 81]], dtype=int32),
 array([[ 2, 91],
        [56, 81],
        [81, 16]], dtype=int32)]

In [94]:
copy_array = arr.copy()

In [95]:
arr

array([[71, 86, 73, 89, 77, 93],
       [22, 64, 36, 73, 21, 28],
       [13, 10, 23, 75, 52, 66],
       [78, 65, 37, 63, 83, 29],
       [29, 18, 74, 24, 72, 58],
       [45, 44, 32, 36, 46, 33]], dtype=int32)

In [96]:
copy_array

array([[71, 86, 73, 89, 77, 93],
       [22, 64, 36, 73, 21, 28],
       [13, 10, 23, 75, 52, 66],
       [78, 65, 37, 63, 83, 29],
       [29, 18, 74, 24, 72, 58],
       [45, 44, 32, 36, 46, 33]], dtype=int32)

In [98]:
copy_array[0,0]=1000
copy_array

array([[1000,   86,   73,   89,   77,   93],
       [  22,   64,   36,   73,   21,   28],
       [  13,   10,   23,   75,   52,   66],
       [  78,   65,   37,   63,   83,   29],
       [  29,   18,   74,   24,   72,   58],
       [  45,   44,   32,   36,   46,   33]], dtype=int32)

In [99]:
arr

array([[71, 86, 73, 89, 77, 93],
       [22, 64, 36, 73, 21, 28],
       [13, 10, 23, 75, 52, 66],
       [78, 65, 37, 63, 83, 29],
       [29, 18, 74, 24, 72, 58],
       [45, 44, 32, 36, 46, 33]], dtype=int32)