In [ ]:
数据分析三剑客

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
import matplotlib as mpl

## <b>1、Series</b>

一维数组：有序的数据类型相同的集合
Series:一维数组的强化版，增加了像字典一样的key-value的访问机制，同时保留了数组的访问机制

字典：无序的集合

Series是一种类似于一维数组的对象，有下面两个部分组成：
* values:一组数据
* index：相关的数据索引标签
 

In [9]:
# 用np.arr构造
arr = np.ones(shape=5)
s1 = Series(arr)
s1

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64

In [10]:
arr[0]=6

In [11]:
s1

0    6.0
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64

In [7]:
# 用列表构造
names = ["Wood","luuna","jaca","Irving"]
s = Series(names)

In [6]:
names

['Wood', 'luuna', 'jaca', 'Irving']

In [4]:
s

0      Wood
1     luuna
2      jaca
3    Irving
dtype: object

In [12]:
names[0] = "WOOD"

In [13]:
s

0      Wood
1     luuna
2      jaca
3    Irving
dtype: object

In [14]:
names

['WOOD', 'luuna', 'jaca', 'Irving']

In [16]:
# 如果没有手动指定显示索引，则使用隐士索引自动填充
s2 = Series(names, index=["key1","key2","key4","key3",])
s2

key1      WOOD
key2     luuna
key4      jaca
key3    Irving
dtype: object

由字典创建

In [23]:
dict1 = {
    "k1":"Wood",
    "k3":"luuna",
    "k2":"cooper"
}
# index的优先级要高于字典键值的优先级
s3 = Series(data=dict1, index=["k1","k2"])
s3

k1      Wood
k2    cooper
dtype: object

In [24]:
arr = np.array([150,150,150,300])
arr

array([150, 150, 150, 300])

In [30]:
cj = Series(arr,index=["语文","数学","英语","理综"])
cj

语文    150
数学    150
英语    150
理综    300
dtype: int64

In [32]:
dic = {
    "语文":150,
    "数学":150,
    "英语":150,
    "理综":300
}
Series(data = dic)

语文    150
数学    150
英语    150
理综    300
dtype: int64

Series的索引和切片

In [33]:
arr = np.random.randint(0,100,size=5)
arr

array([90, 72, 70, 81, 86], dtype=int32)

In [34]:
arr[0]

np.int32(90)

In [36]:
arr[[0,0,2,2]]

array([90, 90, 70, 70], dtype=int32)

In [37]:
arr[[True,True,False,False,False]]

array([90, 72], dtype=int32)

In [38]:
# 1.Series的访问，完全兼容numpy数组访问
s = Series(data=arr, index= ["Wood","luuna","jaca","Irving","lila"])
s

Wood      90
luuna     72
jaca      70
Irving    81
lila      86
dtype: int32

In [39]:
s[0]

C:\Users\13202\AppData\Local\Temp\ipykernel_10684\243613605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]


np.int32(90)

In [41]:
s[[0,1,0,1]]

C:\Users\13202\AppData\Local\Temp\ipykernel_10684\701055087.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[[0,1,0,1]]


Wood     90
luuna    72
Wood     90
luuna    72
dtype: int32

In [42]:
s[[True,True,False,False,False]]

Wood     90
luuna    72
dtype: int32

In [43]:
# 2.使用显示索引访问,类似字典
s["lila"]

np.int32(86)

In [44]:
s[["Wood","jaca"]]

Wood    90
jaca    70
dtype: int32

In [45]:
# 3.使用loc访问，要配合显示索引,官方推荐
s.loc["lila"]

np.int32(86)

In [46]:
s.loc[["Wood","Wood"]]

Wood    90
Wood    90
dtype: int32

In [47]:
# 4。使用iloc，配合隐士索引访问，官方推荐的隐士索引的访问机制
s.iloc[0]

np.int32(90)

In [48]:
s

Wood      90
luuna     72
jaca      70
Irving    81
lila      86
dtype: int32

In [49]:
s.iloc[[0,1,2,1]]

Wood     90
luuna    72
jaca     70
luuna    72
dtype: int32

In [64]:
# 5. 使用带索引的bool型的Series列表访问
# 【注意】如果使用Series的Bool列表要注意索引对齐，顺序不要求一致，内容要求一致，长度一致
s_bool = Series(data=[True,True,False,False,False],index=["lila","luuna","jaca","Irving","Wood"])
# 【注意】bool列表和要访问的对象的长度保持一致
n_bool = [True,True,False,False,False]
l_bool = np.array([True,True,False,False,False])

In [65]:
s[s_bool]

luuna    72
lila     86
dtype: int32

In [60]:
s[s > 80]

Wood      90
Irving    81
lila      86
dtype: int32

<b> 切片</b>
1. 数组
2. 字典
3. .loc
4. .iloc

In [66]:
s

Wood      90
luuna     72
jaca      70
Irving    81
lila      86
dtype: int32

In [67]:
s[1:3]

luuna    72
jaca     70
dtype: int32

In [75]:
# 所有看使用标签（显示索引）切片的都是闭区间
s["luuna":"Irving"]

luuna     72
jaca      70
Irving    81
dtype: int32

In [74]:
# 使用loc访问是闭区间
s.loc["luuna":"jaca"]

luuna    72
jaca     70
dtype: int32

In [73]:
# 使用iloc访问是开区间
s.iloc[1:3]

luuna    72
jaca     70
dtype: int32

In [77]:
dic = {
    "语文":150,
    "数学":150,
    "英语":150,
    "理综":300
}

s_score = Series(data = dic)
s_score

语文    150
数学    150
英语    150
理综    300
dtype: int64

In [80]:
s_score[1]
s_score["数学"]
s_score.loc["数学"]
s_score.iloc[1]

C:\Users\13202\AppData\Local\Temp\ipykernel_10684\409137349.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s_score[1]


np.int64(150)

In [82]:
s_score[0:3]
s_score["语文":"英语"]
s_score.loc["语文":"英语"]
s_score.iloc[0:3]

语文    150
数学    150
英语    150
dtype: int64

In [83]:
s_score.shape

(4,)

In [84]:
s_score.size

4

In [86]:
# 获取显示索引
# Series(data,index)
s_score.index[[0,1]]

Index(['语文', '数学'], dtype='object')

In [87]:
s_score.values

array([150, 150, 150, 300])

In [93]:
# eg1.
(s_score.index=="俄文").any()

np.False_

In [95]:
# eg2.
s_score2 = Series(data = np.random.randint(0,150,size=4),index=s_score.index)
s_score2

语文    24
数学    17
英语     3
理综    86
dtype: int32

<b>可以使用head(),tail()分别查看前n个和后n个值</b>

In [97]:
# 是切片操作，但是一般用于查看数据的结构
s_score.head(2)

语文    150
数学    150
dtype: int64

In [99]:
s_score2.tail(1)

理综    86
dtype: int32

In [102]:
dic = {
    "name":"jaca",
    "address":"beijing"
}
s = Series(data = dic,index=["name","address","oldname"])

In [104]:
#any()  查看一个bool列表中是否至少存在一个True
#all()  查看一个bool列表中是否全都是True

In [105]:
s

name          jaca
address    beijing
oldname        NaN
dtype: object

In [107]:
# 查看大量的数据集中是否存在至少一个空值
s.isnull().any()

np.True_

In [110]:
s.notnull().all()

np.False_

<b>Series本身及其实列都有一个name属性</b>

In [113]:
s_score.name="学科"
s_score

语文    150
数学    150
英语    150
理综    300
Name: 学科, dtype: int64

In [116]:
# Name属性，往往会成为二维表格中的列字段名称
Series(data=np.random.randint(0,100,size=5), name="score")

0    80
1    52
2     4
3    11
4    83
Name: score, dtype: int32

In [117]:
score = Series(data=np.random.randint(0,100,size=5),index=list("abcde"), name="score")
score

a    68
b    33
c    79
d    15
e    84
Name: score, dtype: int32

In [119]:
score.sort_values(ascending=False)

e    84
c    79
a    68
b    33
d    15
Name: score, dtype: int32

根据索引排序

In [120]:
score.sort_index(ascending=False)

e    84
d    15
c    79
b    33
a    68
Name: score, dtype: int32

<b>统计值出现的次数</b>

In [123]:
# 假设这是订单表所有订单用户的id字段
# 我们现在统计每一个用户的订单个数
user_id = Series(data=np.random.randint(0,10,100))
user_id.value_counts()

2    15
6    14
8    13
5    11
0    11
7    10
4     8
9     7
3     6
1     5
Name: count, dtype: int64

In [125]:
username = Series(data=["luuna","lila","wood","wood"])
username.value_counts()

wood     2
luuna    1
lila     1
Name: count, dtype: int64

numpy 聚合 sum(), mean(), np.median()

    广播机制

In [127]:
# 1。Series和一个数运算，遵守广播机制
s= Series(data=np.random.randint(0,10,size=5),index=list("ABCDE"))
s

A    6
B    9
C    0
D    6
E    3
dtype: int32

In [128]:
s+1

A     7
B    10
C     1
D     7
E     4
dtype: int32

In [131]:
# Series和numpy运算, 隐式索引对齐
n = np.ones(shape=(2,5))
n

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [133]:
n+s.values

array([[ 7., 10.,  1.,  7.,  4.],
       [ 7., 10.,  1.,  7.,  4.]])

In [135]:
# 这是numpy，它和n运算是numpy之间的运算，遵守广播机制
s.values

array([6, 9, 0, 6, 3], dtype=int32)

In [139]:
n1 = np.ones(shape=5)

In [140]:
# 长度需一致
s+n1

A     7.0
B    10.0
C     1.0
D     7.0
E     4.0
dtype: float64

<b>Series之间的运算</b>

In [147]:
# Series和Series之间运算时，显示索引对齐
s1 = Series(data = np.random.randint(0,10,size=5),index=list("abcde"))
s2 = Series(data = np.random.randint(0,10,size=4),index=list("eabc"))
s1,s2

(a    3
 b    7
 c    3
 d    9
 e    0
 dtype: int32,
 e    6
 a    9
 b    5
 c    5
 dtype: int32)

In [148]:
s1+s2

a    12.0
b    12.0
c     8.0
d     NaN
e     6.0
dtype: float64

In [150]:
s1.add(s2,fill_value=0)

a    12.0
b    12.0
c     8.0
d     9.0
e     6.0
dtype: float64

查看是否保存